### ISSUE TITLE
More readable design graph

### ISSUE THREAD

**Issue by wking** [gvwilson/long-form#2]
Following up on [this blog post][1], the easy way out would be to zoom in a bit and not try to present the whole picture at once.  I expect a nice, interactive, zoom-through-space-style graph-visualization library exists in JavaScript, but I can't find one now.  But turning the graph diagram into a set of linked pages that just show ancestor/descendant graphs for the current node would be fairly straightforward.  For example, the “Collaboration” page would only show the paths passing through that node.  Folks could click on the related entries to see their pages, and gradually walk and internalize the whole graph.

[1]: http://third-bit.com/2016/04/08/trying-to-find-a-form.html

**Comment by gvwilson** [comment]
I agree - I just haven't been able to find an out-of-the-box implementation.
