### ISSUE TITLE
Suggestions from Jackie Kazil

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/long-form#4]
Someone told me to use Python for data science stuff, so I got a data science book in Python that teaches me Pandas, but I don't understand how to make my data usable to pull into Pandas, and I don't know how to share my results. 

* How do I use Python to collect data? 
* How do I use Python to clean data? 
* How do I use Python to share findings?

**Comment by wking** [comment]
On Wed, Apr 27, 2016 at 04:33:53AM -0700, Greg Wilson wrote:
“… but I don't understand how to make my data usable to pull into
Pandas, and I don't know how to share my results.

“* How do I use Python to collect data? 
* How do I use Python to clean data? 
* How do I use Python to share findings?”

I interpret that original question as “How do I access
previously-collected data from Python?”, e.g. reading it from CSV.
Using Python to *collect* raw data (i.e. interfacing with instruments)
is a separate issue, and is more complicated to handle in a
cross-platform, novice lesson.
